/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

/**
 *
 * @author sahan
 */
public class Header extends javax.swing.JPanel {

    /** Creates new form Header */
    public Header() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogRole = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLogName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 53, 53));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogRole.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLogRole.setForeground(new java.awt.Color(255, 255, 255));
        lblLogRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogRole.setText("Sampath Food sales");
        add(lblLogRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/testprofile.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 145, 126));

        lblLogName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLogName.setForeground(new java.awt.Color(255, 255, 255));
        lblLogName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogName.setText("Welcome");
        add(lblLogName, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 150, 230, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogName;
    private javax.swing.JLabel lblLogRole;
    // End of variables declaration//GEN-END:variables

}
